# Generated by Django 3.2.5 on 2021-08-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='mileage',
            field=models.FloatField(max_length=3),
        ),
    ]
